### ISSUE TITLE
Deploy headless

### ISSUE THREAD

**Issue by OleMussmann** [GIScience/openrouteservice-app#288]
How can I deploy `openrouteservice-app` headless? I would like to dockerize it and start it with the `openrouteservice` through a combined `docker-compose`.

First obstacle: the dev mode always tries to `xdg-open`, which will fail with an error on headless mode.
```
UnhandledPromiseRejectionWarning: Error: Exited with code 3
```
If you reach this via google: A solution to prevent that is setting `open: false` in the `Gruntfile.js`.

The next obstacle seems network related. On an EC2 instance I cannot connect to the grunt web server. It always fails with `Unable to connect`, even with all ports open. When launching the `openrouteservice-app` from a docker container, I can only connect when I run `docker run --network host ...`. Wireshark seems to catch plenty of communication via the `50624-50634` or the `53080-53116` range, but exposing these does not seem to fix it.

**Comment by TimMcCauley** [comment]
@OleMussmann we can't help you unfortunately but if you find a solution we'd be happy to hear it!

**Comment by docquantum** [comment]
I had the same issue since I've been working on dockerizing this application. The issue comes from the Gruntfile.js where in the connect directives, the hostname should be 0.0.0.0 rather than localhost. This makes it so that node listens on all interfaces rather than just the local one.

I still get the UnhandledPromiseRejectionWarning: Error: Exited with code 3 issue (with connect), but as @OleMussmann mentioned, setting open (in connect) to false resolves this.

**Comment by docquantum** [comment]
Looking at grunt-contrib-connect documentation notes that the `open` option is meant to open the web-browser upon launching the app. That means, in headless environments, it needs to be set false.

**Comment by TimMcCauley** [comment]
@docquantum I am not sure if I understand what you want to achieve. If you merely want to use the API of openrouteservice, then this repository is wrong. You will want to run https://github.com/GIScience/openrouteservice which exposes a rich API.

**Comment by docquantum** [comment]
I am trying to build a docker stack that has both ors and ors-app on the same network, both in docker containers. I am doing this through docker compose pulling ors from docker hub and I wrote a dockerfile for ors-app and built it locally. After making the described changes above, I did get it working in a docker container, I just have issues with CORS accessing the backend (ors) locally, but I can access the ors public api.

For reference, here's the dockerfile:
```
FROM node:lts-alpine AS build

# Set environment variables
ENV LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8" DEBIAN_FRONTEND="noninteractive" TERM="xterm"

WORKDIR /src

COPY *.json /src/
COPY .snyk .snyk
COPY .bowerrc .bowerrc

RUN apk --no-cache update && apk --no-cache add git \ 
  && npm install \
  && node_modules/bower/bin/bower install --allow-root\
  && cd bower_components/angularjs-slider \
  && npm install \
  && npm audit fix \
  && cd ../../ \
  && npm audit fix 


FROM node:lts-alpine AS production
LABEL MAINTAINER="Daniel Shchur (DocQuantum) <shchurgood@gmail.com>"
ENV API_KEY="" PATH="/app/node_modules/.bin:$PATH"
WORKDIR /app

COPY --from=build /src ./
COPY app app
RUN echo ${API_KEY} > app/weathercheck.txt
COPY Gruntfile.default.js Gruntfile.js
COPY main.js main.js
COPY bs-config.js bs-config.js

EXPOSE 3035 8888

CMD [ "grunt", "production" ]
```

Docker-compose:
```
version: '3'

services:
    ors-back:
        image: giscience/openrouteservice:release_5.0.2
        container_name: ors-back
        restart: on-failure
        expose:
            - 8080
        volumes:
            - /home/rancher/containers/ors-back/graphs:/ors-core/data/graphs
            - /home/rancher/containers/ors-back/elevation_cache:/ors-core/data/elevation_cache
            - /home/rancher/containers/ors-back/logs/ors/:/var/log/ors/
            - /home/rancher/containers/ors-back/logs/tomcat/:/usr/local/tomcat/logs
        healthcheck:
            test: ["CMD", "wget", "http://localhost:8080/ors/health"]
            interval: 1m30s
            timeout: 10s
            retries: 3

    ors-front:
        image: orsapp:latest
        container_name: ors-front
        restart: on-failure
        ports:
            -  8888:8888
```

And directives of my Gruntfile.js
```
production: {
    options: {
        hostname: "0.0.0.0",
        port: 8888,
        base: "./build",
        middleware: function(connect) {
            return [
                connect().use(function (req, res, next) {
                    res.setHeader('Access-Control-Allow-Origin', '*');
                    return next();
                }),
                //modRewrite(['^[^\\.]*$ /index.html [L]']),
                modRewrite([
                    "!\\.html|\\.js|\\.txt|\\.ico|\\.svg|\\.map|\\.woff2|\\.woff|\\.ttf|\\.css|\\.png$ /index.html [L]"
                ]),
                serveStatic("./build")
            ];
        }
    }
}

...

build: {
    options: {
        dest: "app/js/config.js"
    },
    constants: {
        ENV: {
            name: "build",
            // change name_of_war_archive to the name of the ors backend war version you are using (e.g. openrouteservice-4.4.0)
            geocode:
                "http://ors-back:8080/ors/geocode",
            directions:
                "http://ors-back:8080/ors/routes",
            isochrones:
                "http://ors-back:8080/ors/isochrones",
            matrix:
                "http://ors-back:8080/ors/matrix",
            pois:
                "https://api.openrouteservice.org/pois",
            shortenlink: "https://api-ssl.bitly.com/v3/shorten",
            mapsurfer:
                "https://api.openrouteservice.org/mapsurfer/{z}/{x}/{y}.png",
            landmarks: 'https://landmarks-api.openrouteservice.org/',
            fuel: "https://api.openrouteservice.org/fuel"
        }
    }
}
```

I am currently running both of these on a headless server running RancherOS (docker-only OS).

I am documenting my findings on this issue thread in case others wish to run headless as well and wish to find a way to run this application in a docker container for testing or production.

**Comment by Doev** [comment]
Hi DocQuantum,

did you manage to dockerize it?

**Comment by docquantum** [comment]
@Doev I haven't worked on it in a while. The issue I was running into was that compiling the maps would take up a substantial amount of memory, leading to crashes which were hard to debug since it was done in a container.

Here's the docker compose I ended up using however:

```
version: '3'

services:
    ors-back:
        image: giscience/openrouteservice:release_5.0.2
        container_name: ors-back
        restart: on-failure
        ports:
            - 8889:8080
        volumes:
            - /home/user/containers/ors-back/graphs:/ors-core/data/graphs
            - /home/usr/containers/ors-back/elevation_cache:/ors-core/data/elevation_cache
            - /home/usr/containers/ors-back/logs/ors/:/var/log/ors/
            - /home/usr/containers/ors-back/logs/tomcat/:/usr/local/tomcat/logs
        healthcheck:
            test: ["CMD", "wget", "http://localhost:8080/ors/health"]
            interval: 1m30s
            timeout: 10s
            retries: 3
    
    ors-front:
        image: orsapp:latest
        container_name: ors-front
        restart: on-failure
        ports:
            -  8888:8888

```

As as a note, our volumes were mounted in a `container` folder which had the open maps files and such it would pull from, along with configurations.

I also built the frontend as a container using this Dockerfile:

```
FROM node:lts-alpine AS build

# Set environment variables
ENV LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8" DEBIAN_FRONTEND="noninteractive" TERM="xterm"

WORKDIR /src

COPY *.json /src/
COPY .snyk .snyk
COPY .bowerrc .bowerrc

RUN apk --no-cache update && apk --no-cache add git \ 
  && npm install \
  && node_modules/bower/bin/bower install --allow-root\
  && cd bower_components/angularjs-slider \
  && npm install \
  && npm audit fix \
  && cd ../../ \
  && npm audit fix 


FROM node:lts-alpine AS production
LABEL MAINTAINER="Daniel Shchur (DocQuantum) <shchurgood@gmail.com>"
ENV API="<API KEY FROM ORS-CORE>" PATH="/app/node_modules/.bin:$PATH"
WORKDIR /app

COPY --from=build /src ./
COPY app app
RUN echo ${API} > app/weathercheck.txt
COPY Gruntfile.default.js Gruntfile.js
COPY main.js main.js
COPY bs-config.js bs-config.js

EXPOSE 3035 8888

CMD [ "grunt", "production" ]
```

I was having CORS issues, something to do with certificates or the service wanting HTTPS. I didn't spend enough time to figure it out, and now I'm running a reverse proxy which could change some things.

If you would like any more stuff, I can send it to you.
